######################## default configuration ####################
baseURL = "https://2021.unpolarised.in/"
languageCode = "en-in"
title = "#unpolarised"
theme = "influencer"
summaryLength = "10"
paginate = 6

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  
  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/magnific-popup.min.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "book"
  weight = 1
  
  [[menu.main]]
  name = "Chapter"
  URL = "chapter"
  weight = 2
  
  [[menu.main]]
  name = "Reviews"
  URL = "review"
  weight = 3
  
  [[menu.main]]
  name = "Author"
  URL = "author"
  weight = 4
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 5
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 6


#################### default parameters ################################
[params]
logo = ""
home = "Home"
# Meta data
description = "This is meta description"
author = "Ram Iyer"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# copyright
copyright = "Copyright &copy; 2021 [Ram Iyer](https://ramiyer.me/) All Rights Reserved"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.navButton]
enable = true

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# Footer ########################
[params.footer]
content = "Each theme featured at the Bootstrap marketplace has been reviewed by Bootstrap's creators.Lorem ipsum dolor sit amet, consectetur adipisicing elit."


############################# post share ###################
[[params.share]]
title = "facebook"
icon = "fa-facebook"
link = "#"

[[params.share]]
title = "twitter"
icon = "fa-twitter"
link = "#"

[[params.share]]
title = "linkedin"
icon = "fa-linkedin-in"
link = "#"

[[params.share]]
title = "whatsapp"
icon = "fa-whatsapp"
link = "#"