######################## default configuration ####################
baseURL = "https://2021.unpolarised.in/"
languageCode = "en-in"
title = "#unpolarised"
theme = "influencer"
summaryLength = "10"
paginate = 6

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  
  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/magnific-popup.min.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "book"
  weight = 1
  
  [[menu.main]]
  name = "Chapters"
  URL = "chapters"
  weight = 2
  
  [[menu.main]]
  name = "Reviews"
  URL = "reviews"
  weight = 3
  
  [[menu.main]]
  name = "Author"
  URL = "author"
  weight = 4


#################### default parameters ################################
[params]
logo = ""
home = "Home"
# Meta data
description = "This is meta description"
author = "Ram Iyer"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# copyright
copyright = "Copyright &copy; 2021 [Ram Iyer](https://ramiyer.me/) All Rights Reserved"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.navButton]
enable = true

# cookies
[params.cookies]
enable = true
expire_days = 1
  
############################# Footer ########################
[params.footer]
content = "This series is dedicated to understanding what is around us, devoid of bias. One must pick a side after knowing all the aspects of an issue. Read the publications to support the author in his endeavour to shed some light on some of the most pressing issues of the day."


############################# post share ###################
[[params.share]]
title = "facebook"
icon = "fa-facebook"
link = "#"

[[params.share]]
title = "twitter"
icon = "fa-twitter"
link = "#"

[[params.share]]
title = "linkedin"
icon = "fa-linkedin-in"
link = "#"

[[params.share]]
title = "whatsapp"
icon = "fa-whatsapp"
link = "#"